using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Teleport : MonoBehaviour
{
    private float countDown = 3f;

    /*
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        countDown -= Time.deltaTime;
        if(countDown <= 0)
        {
            Destroy(gameObject);
        }
    }
    */

    public void SetTeleport()
    {
        gameObject.SetActive(true);
        Invoke("EndTeleport", countDown);
    }

    public void EndTeleport()
    {
        gameObject.SetActive(false);
    }
}
